# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-25 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedPoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('contact', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('cnic', models.CharField(max_length=300)),
            ],
        ),
    ]
